version:  '3'

services:
  api:
    build: .            # build Dockerfile
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    # restart: on-failure
    volumes:
      - .:/app
    ports:
      - "8080:8080"
